server:
  port: 8083
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: localhost
      ms-client: localhost
      ms-credits: localhost
      ms-loan: localhost
      ms-debit-card: localhost
      ms-mobile-wallet: localhost
spring:
  application:
    name: service-movement
  data:
    mongodb:
      uri: mongodb://localhost:27017/MovementsDB
      auto-index-creation: true
  config:
    import: optional:configserver:http://ms-config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      creditCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
      bankaccountCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
      mobilewalletCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        
message:
  demo: leido desde local